/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Badge: typeof import('./src/components/ui/badge/Badge.vue')['default']
    Button: typeof import('./src/components/ui/button/Button.vue')['default']
    Card: typeof import('./src/components/ui/card/Card.vue')['default']
    CardContent: typeof import('./src/components/ui/card/CardContent.vue')['default']
    CardDescription: typeof import('./src/components/ui/card/CardDescription.vue')['default']
    CardFooter: typeof import('./src/components/ui/card/CardFooter.vue')['default']
    CardHeader: typeof import('./src/components/ui/card/CardHeader.vue')['default']
    CardTitle: typeof import('./src/components/ui/card/CardTitle.vue')['default']
    DashboardLogo: typeof import('./src/views/Dashboard/DashboardLogo.vue')['default']
    DashboardMenu: typeof import('./src/views/Dashboard/DashboardMenu.vue')['default']
    DashboardView: typeof import('./src/views/Dashboard/DashboardView.vue')['default']
    Dialog: typeof import('./src/components/ui/dialog/Dialog.vue')['default']
    DialogContent: typeof import('./src/components/ui/dialog/DialogContent.vue')['default']
    DialogDescription: typeof import('./src/components/ui/dialog/DialogDescription.vue')['default']
    DialogHeader: typeof import('./src/components/ui/dialog/DialogHeader.vue')['default']
    DialogTitle: typeof import('./src/components/ui/dialog/DialogTitle.vue')['default']
    DialogTrigger: typeof import('./src/components/ui/dialog/DialogTrigger.vue')['default']
    EstadoPostulacionTimeline: typeof import('./src/components/Postulantes/EstadoPostulacionTimeline.vue')['default']
    HomeView: typeof import('./src/views/Dashboard/HomeView.vue')['default']
    Input: typeof import('./src/components/ui/input/Input.vue')['default']
    NotFound: typeof import('./src/views/NotFound.vue')['default']
    PostulanteDetalle: typeof import('./src/components/Postulantes/PostulanteDetalle.vue')['default']
    PostulantesFiltros: typeof import('./src/components/Postulantes/PostulantesFiltros.vue')['default']
    PostulantesStats: typeof import('./src/components/Postulantes/PostulantesStats.vue')['default']
    PostulantesView: typeof import('./src/views/Dashboard/PostulantesView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sheet: typeof import('./src/components/ui/sheet/Sheet.vue')['default']
    SheetClose: typeof import('./src/components/ui/sheet/SheetClose.vue')['default']
    SheetContent: typeof import('./src/components/ui/sheet/SheetContent.vue')['default']
    SheetDescription: typeof import('./src/components/ui/sheet/SheetDescription.vue')['default']
    SheetFooter: typeof import('./src/components/ui/sheet/SheetFooter.vue')['default']
    SheetHeader: typeof import('./src/components/ui/sheet/SheetHeader.vue')['default']
    SheetTitle: typeof import('./src/components/ui/sheet/SheetTitle.vue')['default']
    SheetTrigger: typeof import('./src/components/ui/sheet/SheetTrigger.vue')['default']
    Table: typeof import('./src/components/ui/table/Table.vue')['default']
    TableBody: typeof import('./src/components/ui/table/TableBody.vue')['default']
    TableCell: typeof import('./src/components/ui/table/TableCell.vue')['default']
    TableHead: typeof import('./src/components/ui/table/TableHead.vue')['default']
    TableHeader: typeof import('./src/components/ui/table/TableHeader.vue')['default']
    TableRow: typeof import('./src/components/ui/table/TableRow.vue')['default']
    Toast: typeof import('./src/components/ui/toast/Toast.vue')['default']
    ToastAction: typeof import('./src/components/ui/toast/ToastAction.vue')['default']
    ToastClose: typeof import('./src/components/ui/toast/ToastClose.vue')['default']
    ToastDescription: typeof import('./src/components/ui/toast/ToastDescription.vue')['default']
    Toaster: typeof import('./src/components/ui/toast/Toaster.vue')['default']
    ToastProvider: typeof import('./src/components/ui/toast/ToastProvider.vue')['default']
    ToastTitle: typeof import('./src/components/ui/toast/ToastTitle.vue')['default']
    ToastViewport: typeof import('./src/components/ui/toast/ToastViewport.vue')['default']
  }
}
